#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.2
#  in conjunction with Tcl version 8.6
#    May 19, 2020 06:33:52 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from gui.support import *
import os.path


def vp_start_gui(node):
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = Toplevel1(root)
    init(root, top, node)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font8 = "-family {Arial} -size 12"
        font14 = "-family {Arial} -size 22"
        font16 = "-family {Arial} -size 21"

        top.geometry("594x425+665+65")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(0, 0)
        top.title("New Toplevel")
        top.configure(background="#f8da5b")

        self.upload = tk.Button(top)
        self.upload.place(relx=0.158, rely=0.8, height=64, width=177)
        self.upload.configure(activebackground="#ffffff")
        self.upload.configure(activeforeground="#000000")
        self.upload.configure(background="#17dd0d")
        self.upload.configure(disabledforeground="#a3a3a3")
        self.upload.configure(font=font14)
        self.upload.configure(foreground="#ffffff")
        self.upload.configure(highlightbackground="#d9d9d9")
        self.upload.configure(highlightcolor="black")
        self.upload.configure(pady="0")
        self.upload.configure(text='''UPLOAD''')
        self.upload.bind('<Button-1>', lambda p: upload())

        self.download = tk.Button(top)
        self.download.place(relx=0.547, rely=0.8, height=64, width=177)
        self.download.configure(activebackground="#ececec")
        self.download.configure(activeforeground="#000000")
        self.download.configure(background="#ff8000")
        self.download.configure(disabledforeground="#a3a3a3")
        self.download.configure(font=font16)
        self.download.configure(foreground="#ffffff")
        self.download.configure(highlightbackground="#d9d9d9")
        self.download.configure(highlightcolor="black")
        self.download.configure(pady="0")
        self.download.configure(text='''DOWNLOAD''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.051, rely=-0.047, height=271, width=538)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        photo_location = "gui/background.png"
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)
        self.Label1.configure(text='''Label''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.264, rely=0.635, height=30, relwidth=0.461)
        self.Entry1.configure(background="#fcedb1")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.files = tk.Button(top)
        self.files.place(relx=0.725, rely=0.635, height=30, width=30)
        self.files.configure(background="#ff8000")
        self.files.configure(disabledforeground="#a3a3a3")
        self.files.configure(foreground="#ffffff")
        self.files.configure(highlightbackground="#d9d9d9")
        self.files.configure(highlightcolor="black")
        self.files.configure(pady="0")
        photo_location = "gui/foldericon.png"
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.files.configure(image=_img1)
        self.files.bind('<Button-1>', lambda p:file_path())

        self.status_lable = tk.Label(top)
        self.status_lable.place(relx=0.0, rely=0.7, height=30, relwidth=1)
        self.status_lable.configure(background="#f8da5b")
        self.status_lable.configure(text='''''')
        self.status_lable.configure(font=font8)
        self.status_lable.configure(foreground="#ff0000")


if __name__ == '__main__':
    vp_start_gui()
