#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.2
#  in conjunction with Tcl version 8.6
#    May 19, 2020 06:33:42 PM +0300  platform: Windows NT


import time

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

try:
    from tkinter import filedialog
except ImportError:
    from tkinter import filedialog


def init(top, gui, node1, *args, **kwargs):
    global w, top_level, root, entry, status_lable, node
    node = node1
    w = gui
    top_level = top
    root = top
    entry = w.Entry1
    status_lable = w.status_lable


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def file_path():
    file_name = filedialog.askopenfile()
    set_entry_text(file_name.name)


def upload():
    file_path = entry.get()
    set_entry_text('')
    file_name = file_path.split('/')[-1]
    print('upload file', file_path, 'as', file_name)
    set_status_lable_text('uploading ' + file_path + ' to the network', 'good')
    node.store_file(file_name, file_path)
    set_status_lable_text('file have been shared to the web successfully', 'good')


def download():
    file_name = entry.get()
    set_entry_text('')
    set_status_lable_text('searching ' + file_name + ' in the network', 'good')
    status = node.download(file_name)
    if status[:5] == 'ERROR':
        set_status_lable_text(status, 'bad')
    else:
        set_status_lable_text(status, 'good')


def set_entry_text(text):
    entry.delete(0, 'end')
    entry.insert(0, text)
    return


def set_status_lable_text(text, status):
    status_lable.configure(text=text)
    # if status is good text text will be green, if it bad it will be red
    if status == 'good':
        status_lable.configure(foreground="#17dd0d")
    elif status == 'bad':
        status_lable.configure(foreground="#ff0000")


if __name__ == '__main__':
    import unknown
    unknown.vp_start_gui()


